config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/index'
  get 'static_pages/after_signup'

  devise_for :users, controllers: { registrations: 'registrations' }
  resources :groups, except: [:show]

  post 'order_items/create',          to: 'order_items#create'
  patch 'order_items/:id',            to: 'order_items#update'
  put 'order_items/:id',              to: 'order_items#update'
  delete 'order_items/:id',           to: 'order_items#delete'
  post 'order_items/create/item',     to: 'order_items#create_item'
  post 'order_items/create/assembly', to: 'order_items#create_assembly'

  resources :locations, except: [:show]
  resources :departments
  resources :orders do
    # TODO: use nested resources for routes declared above
    # resources :order_items

    post '/duplicate', to: 'orders#duplicate'
    delete '/assembly/:assembly_id', to: 'orders#delete_assembly', as: 'assembly'
  end
  resources :assemblies, except: [:show]
  resources :items, except: [:show]
  resources :location_departments, only: [:create, :update, :destroy]
  post 'location_departments/:id/:direction', to: 'location_departments#change_direction'
  resources :meal_schedules

  root to: 'orders#index'
end

app/models/group.rb
=begin

id:           integer
name:         string
description:  string
created_at:   datetime
updated_a:    datetime

=end
class Group < ApplicationRecord
  has_many :user_groups, dependent: :destroy
  has_many :users, through: :user_groups

  validates :name, presence: true, uniqueness: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @user = current_user
    @group = @user.groups.create(group_params)

    respond_to do |format|
      if @group.save && @user.save
        format.html { redirect_to groups_url, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: groups_url }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to groups_url, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: groups_url }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def group_params
      params.require(:group).permit(:name, :description, user_ids:[])
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_empty_group_list.html.erb
<div class="island">
    <div class="island-hd">
        <h2 class="hdg hdg_1">
            Groups
        </h2>
    </div>
    <div class="island-bd">
        <span class="txt-sansSerif">You don't have any groups yet.  Create a <%= link_to 'New Group', new_group_path, class: 'link' %>
    </div>
</div>

app/views/groups/_form.html.erb
<%= simple_form_for(@group, html: { autocomplete: 'off' }) do |f| %>
    <div class="island-bd">
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

        <div class="vr_3">
            <div class="vr_2">
                <div class="form-group mix-form-group_full">
                    <%= f.label :name %>
                </div>
                <div class="form-group mix-form-group_full">
                    <%= f.input_field :name, placeholder: 'name', autofocus: true, class: 'input-text' %>
                </div>
                <div class="form-group mix-form-group_full">
                    <%= f.error :name, id: 'name_error' %>
                </div>
            </div>

            <div class="vr_2">
                <div class="form-group mix-form-group_full">
                    <%= f.label :description %>
                </div>
                <div class="form-group mix-form-group_full">
                    <%= f.text_area :description, placeholder: 'description', class: 'input-text', rows: 5 %>
                </div>
                <div class="form-group mix-form-group_full">
                    <%= f.error :description, id: 'description_error' %>
                </div>
            </div>
        </div>

        <div class="form-group">
            <%= f.button :submit, class: "btn btn-submit mix-btn_inverse" %>
        </div>
    </div>
<% end %>

app/views/groups/_group_list.html.erb
<h2 class="hdg hdg_1">Groups</h2>

<ul class="stero">
    <% @groups.each do |group| %>
        <li class="listItem">
            <div class="listItem-hd">
                <ul class="stereo">
                    <li>
                        <%= link_to group.name, edit_group_path(group), class: 'link' %>
                    </li>
                    <li>
                        <%= button_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn' %>
                    </li>
                </ul>
            </div>
        </li>
    <% end %>
</ul>

app/views/groups/edit.html.erb
<ul class="stereo">
    <li>
        <h2 class="hdg hdg_1">
            Edit Group
        </h2>
    </li>
    <li>
        <%= link_to 'Back', groups_path, class: 'link' %>
    </li>
</ul>

<div class="island">
    <div class="island-bd">
        <%= render 'form', group: @group %>
    </div>
</div>

app/views/groups/index.html.erb
<% if !current_user.has_groups? %>
    <%= render partial: 'empty_group_list'%>
<% else %>
    <%= render partial: 'group_list' %>
<% end %>

app/views/groups/new.html.erb
<ul class="stereo">
    <li>
        <h2 class="hdg hdg_1">
            New Group
        </h2>
    </li>
    <li>
        <%= link_to 'Back', groups_path, class: 'link' %>
    </li>
</ul>

<div class="island">
    <div class="island-bd">
        <%= render 'form', group: @group %>
    </div>
</div>