config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/index'
  get 'static_pages/after_signup'

  devise_for :users, controllers: { registrations: 'registrations' }
  resources :groups, except: [:show]

  post 'order_items/create',          to: 'order_items#create'
  patch 'order_items/:id',            to: 'order_items#update'
  put 'order_items/:id',              to: 'order_items#update'
  delete 'order_items/:id',           to: 'order_items#delete'
  post 'order_items/create/item',     to: 'order_items#create_item'
  post 'order_items/create/assembly', to: 'order_items#create_assembly'

  resources :locations, except: [:show]
  resources :departments
  resources :orders do
    # TODO: use nested resources for routes declared above
    # resources :order_items

    post '/duplicate', to: 'orders#duplicate'
    delete '/assembly/:assembly_id', to: 'orders#delete_assembly', as: 'assembly'
  end
  resources :assemblies, except: [:show]
  resources :items, except: [:show]
  resources :location_departments, only: [:create, :update, :destroy]
  post 'location_departments/:id/:direction', to: 'location_departments#change_direction'
  resources :meal_schedules

  root to: 'orders#index'
end

app/models/order.rb
=begin

id:             integer
status:         string
created_at:     datetime
updated_at:     datetime
location_id:    datetime
shopping_date:  datetime

=end
class Order < ApplicationRecord
  belongs_to :location, optional: true

  has_many :assemblies, through: :order_items
  has_many :items, through: :assemblies
  has_many :departments, through: :order_items
  has_many :order_items, dependent: :destroy

  validates :status, inclusion: {
    in: %w(pending active cancelled complete),
    message: "%{value} is not a valid status"
  }, presence: true
  validates :shopping_date, presence: true

  scope :active, -> { where(status: 'active') }
  scope :pending, -> { where(status: 'pending') }
  scope :finished, -> { where.not(status: ['active', 'pending']) }

  # TODO: shared method used in Item, should be abstracted
  def group_by_department
    self.order_items.group_by(&:department)
  end

  def group_by_department_and_sort
    self.group_by_department.sort_by { |k, v| k.name.to_s }
  end

  def delete_assembly(id)
    order_items_to_remove = self.order_items.where(assembly_id: id)

    return nil if !self.live? || order_items_to_remove.size == 0

    order_items_to_remove.destroy_all
  end

  def duplicate
    return nil if Order.pending.count > 0

    duplicate_order = Order.new(status: 'pending', location_id: self.location_id, shopping_date: Time.now)
    duplicate_order.order_items << self.order_items.map { |order_item| order_item.duplicate(duplicate_order.id) }

    duplicate_order
  end

  def live?
    self.status == 'pending' || self.status == 'active'
  end

  def finished_by_shopping_date
    self.finished.order('shopping_date DESC')
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all.order('status DESC')
    @orders_finished_by_shopping_date = Order.finished.order('shopping_date DESC')
    @locations = Location.all.order('id ASC')
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @departments = Department.all
    @assemblies = Assembly.all
    @items = Item.all
    @locationDepartments = LocationDepartment.find_all_by_location_id(@order.location_id)
  end

  # GET /orders/new
  def new
    @order = Order.new(shopping_date: Time.now)
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to orders_path, notice: 'Order was created successfully' }
        format.json { render :show, status: :created, location: orders_path }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was updated successfully' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # POST /orders/1/duplicate
  # POST /orders/1/duplicate.json
  def duplicate
    order = Order.find(params[:order_id])
    duplicate_order = order.duplicate

    respond_to do |format|
      if duplicate_order != nil && duplicate_order.save
        format.html { redirect_to edit_order_url(duplicate_order.id), notice: 'Order duplicated successfully' }
        format.json { render :show, status: :created, location: orders_path }
      else
        format.html { redirect_to edit_order_url(order.id) }
        format.json { render :show, status: :created, location: orders_path }
      end
    end
  end

  # DELETE /orders/1/assembly/1
  # DELETE /orders/1/assembly/1.json
  def delete_assembly
    order = Order.find(params[:order_id])

    respond_to do |format|
      if order.delete_assembly(params[:assembly_id])
        format.html { redirect_to order_url(order.id, order: 'assembly'), notice: 'Assembly deleted successfully' }
        format.json { render :show, status: 204, location: orders_path }
      else
        format.html { redirect_to order_url(order.id) }
        format.json { render :show, status: 204, location: orders_path }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:status, :location_id, :shopping_date)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= simple_form_for(@order) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="vr_1">
        <div class="form-group">
            <%= f.input :status, collection: ['pending', 'active', 'cancelled', 'complete'], include_blank: false %>
        </div>
        <div class="form-group">
            <%= f.association :location, include_blank: false %>
        </div>
        <div class="form-group">
            <%= f.input :shopping_date, as: :date, html5: true, :input_html => { :class => 'input-date' } %>
        </div>
    </div>

    <div class="form-actions">
        <%= f.button :submit, :class => 'btn-submit mix-btn_inverse' %>
    </div>
<% end %>

app/views/orders/edit.html.erb
<div class="stereo">
    <div>
        <h1 class="hdg hdg_1">Editing Order</h1>
    </div>
    <div>
        <ul class="hlist hlist-divided">
            <li>
                <%= link_to 'Back', orders_path, class: "link" %>
            </li>
            <li>
                <%= link_to 'Show', @order, class: "link" %>
            </li>
            <li>
                <%= link_to 'Destroy', @order, method: :delete, data: { confirm: 'Are you sure?' }, class: "link" %>
            </li>
        </ul>
    </div>
</div>

<%= render 'form', order: @order %>

app/views/orders/index.html.erb
<ul class="stereo">
    <li>
        <h1 class="hdg hdg_1">Orders</h1>
    </li>
    <li>
        <%= link_to 'New Order', new_order_path, class: "link" %>
    </li>
</ul>
<%= react_component(
    'OrderListContainer',
    locations: @locations,
    ordersByConcern: [
        {
            name: 'Pending',
            items: @orders.pending,
            renderer: 'card',
        },
        {
            name: 'Active',
            items: @orders.active,
            renderer: 'card',
        },
        {
            name: 'Finished',
            items: @orders_finished_by_shopping_date,
            renderer: 'simple',
        },
    ]
) %>

app/views/orders/new.html.erb
<div class="stereo">
    <div>
        <h1 class="hdg hdg_1">New Order</h1>
    </div>
    <div>
        <%= link_to 'Back', orders_path, class: "link" %>
    </div>
</div>

<%= render 'form', order: @order %>

app/views/orders/show.html.erb
<div class="vr_1">
    <ul class="stereo">
        <li>
            <h1 class="hdg hdg_1">Order</h1>
        </li>
        <li>
            <ul class="hlist hlist-divided">
                <li>
                    <%= link_to 'Back', orders_path, class: "link" %>
                </li>
                    <% if @order.status != 'pending' %>
                        <li>
                            <%= link_to 'Duplicate', order_duplicate_path(@order), method: :post, class: "link" %>
                        </li>
                    <% end %>
                <li>
                    <%= link_to 'Edit', edit_order_path(@order), class: "link" %>
                </li>
                <li>
                    <%= link_to 'Destroy', @order, method: :delete, data: { confirm: 'Are you sure?' }, class: "link" %>
                </li>
            </ul>
        </li>
    </ul>
</div>

<%= react_component(
    'OrderPage',
    csrf: form_authenticity_token,
    departments: @departments,
    assemblies: @assemblies,
    orderItems: @order.order_items,
    items: @items,
    locationDepartments: @locationDepartments,
    order: @order,
    orderLocation: @order.location
) %>