config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/index'
  get 'static_pages/after_signup'

  devise_for :users, controllers: { registrations: 'registrations' }
  resources :groups, except: [:show]

  post 'order_items/create',          to: 'order_items#create'
  patch 'order_items/:id',            to: 'order_items#update'
  put 'order_items/:id',              to: 'order_items#update'
  delete 'order_items/:id',           to: 'order_items#delete'
  post 'order_items/create/item',     to: 'order_items#create_item'
  post 'order_items/create/assembly', to: 'order_items#create_assembly'

  resources :locations, except: [:show]
  resources :departments
  resources :orders do
    # TODO: use nested resources for routes declared above
    # resources :order_items

    post '/duplicate', to: 'orders#duplicate'
    delete '/assembly/:assembly_id', to: 'orders#delete_assembly', as: 'assembly'
  end
  resources :assemblies, except: [:show]
  resources :items, except: [:show]
  resources :location_departments, only: [:create, :update, :destroy]
  post 'location_departments/:id/:direction', to: 'location_departments#change_direction'
  resources :meal_schedules

  root to: 'orders#index'
end

app/models/location.rb
=begin

id:           integer
name:         string
city:         string
state:        string
created_at:   datetime
updated_a:    datetime

=end
class Location < ApplicationRecord
  has_many :orders, dependent: :destroy
  has_many :location_departments, dependent: :nullify
  has_many :departments, through: :location_departments, dependent: :nullify

  validates :name, presence: true, uniqueness: true

  scope :by_name, -> { order('name ASC') }

  def city_and_state
    "#{self.city}, #{self.state}"
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @location = Location.new
    @locations = Location.by_name
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
    @location_departments = LocationDepartment.find_all_by_location_id(params[:id])
    @departments = Department.all
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to locations_url, notice: 'Location was created successfully' }
        format.json { render :show, status: :created, location: locations_url }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/:id
  # PATCH/PUT /locations/:id.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to locations_url, notice: 'Location was updated successfully' }
        format.json { render :show, status: :ok, location: locations_url }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:name, :city, :state)
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<div class="vr_4">
    <%= simple_form_for(@location) do |f| %>
        <div class="vr_2">
            <%= f.error_notification %>
            <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

            <div class="form-group">
                <%= f.input :name, :input_html => { :class => 'input-text' } %>
            </div>
            <div class="form-group">
                <%= f.input :city, :input_html => { :class => 'input-text' } %>
            </div>
            <div class="form-group">
                <%= f.input :state, :input_html => { :class => 'input-text' } %>
            </div>
        </div>

        <ul class="hlist">
            <% if !current_page?(locations_path) %>
                <li>
                    <%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' }, class: "link" %>
                </li>
            <% end %>
            <li>
                <%= f.button :submit, :class => 'btn-submit mix-btn_inverse'  %>
            </li>
        </ul>
    <% end %>
</div>

app/views/locations/edit.html.erb
<ul class="stereo">
    <li>
        <h1 class="hdg hdg_1">Edit Location</h1>
    </li>
    <li>
        <ul class="hlist hlist-divided">
            <li>
                <%= link_to 'Back', locations_path, class: "link" %>
            </li>
            <li>
                <%= link_to 'New', new_location_path, class: "link" %>
            </li>
        </ul>
    </li>
</ul>

<%= render 'form', location: @location %>

<%= react_component(
    'LocationDepartmentsPage',
    csrf: form_authenticity_token,
    departments: @departments,
    locationDepartments: @location_departments,
    locationId: @location.id
) %>

app/views/locations/index.html.erb
<%= render partial: "shared/flyoutable_with_form", locals: { flyoutable: @location } %>
<ul class="stereo">
    <li>
        <h1 class="hdg hdg_1">Locations</h1>
    </li>
    <li>
        <a href="#" class="link js-flyout-trigger">New Location</a>
    </li>
</ul>
<ul class="vlist">
    <% @locations.each do |location| %>
        <li class="listItem">
            <div class="listItem-hd">
                <ul class="stereo">
                    <li>
                        <%= link_to location.name, edit_location_path(location), class: "link" %>
                    </li>
                    <li>
                        <%= button_to 'Destroy', location, method: :delete, class: 'btn', data: { confirm: 'Are you sure?' } %>
                    </li>
                </ul>
            </div>
            <div class="listItem-ft">
                <%= location.city_and_state %>
            </div>
        </li>
    <% end %>
</ul>

app/views/locations/new.html.erb
<div class="stereo">
    <div>
        <h1 class="hdg hdg_1">New Location</h1>
    </div>
    <div>
        <%= link_to 'Back', locations_path, class: "link" %>
    </div>
</div>

<%= render 'form', location: @location %>