config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/index'
  get 'static_pages/after_signup'

  devise_for :users, controllers: { registrations: 'registrations' }
  resources :groups, except: [:show]

  post 'order_items/create',          to: 'order_items#create'
  patch 'order_items/:id',            to: 'order_items#update'
  put 'order_items/:id',              to: 'order_items#update'
  delete 'order_items/:id',           to: 'order_items#delete'
  post 'order_items/create/item',     to: 'order_items#create_item'
  post 'order_items/create/assembly', to: 'order_items#create_assembly'

  resources :locations, except: [:show]
  resources :departments
  resources :orders do
    # TODO: use nested resources for routes declared above
    # resources :order_items

    post '/duplicate', to: 'orders#duplicate'
    delete '/assembly/:assembly_id', to: 'orders#delete_assembly', as: 'assembly'
  end
  resources :assemblies, except: [:show]
  resources :items, except: [:show]
  resources :location_departments, only: [:create, :update, :destroy]
  post 'location_departments/:id/:direction', to: 'location_departments#change_direction'
  resources :meal_schedules

  root to: 'orders#index'
end

app/views/layouts/_footer.html.erb
<% if user_signed_in? %>
    <nav>
        <ul class="footer-nav">
            <li class="footer-nav-item">
                <%= link_to 'Departments', departments_path, class: "link" %>
            </li>
            <li class="footer-nav-item">
                <%= link_to 'Schedules', meal_schedules_path, class: "link" %>
            </li>
            <li class="footer-nav-item">
                <%= link_to 'Locations', locations_path, class: "link" %>
            </li>
        </ul>
    </nav>
<% end %>

app/views/layouts/_header.html.erb
<header class="header">
    <% if user_signed_in? %>
        <input
            type="checkbox"
            name="mobileMenu-toggle"
            id="mobileMenu-toggle"
            class="mobileMenu-toggle u-isHidden"
        />
        <input
            type="checkbox"
            name="mobileMenu-user-toggle"
            id="mobileMenu-user-toggle"
            class="mobileMenu-user-toggle u-isHidden"
        />

        <div class="header-nav-container">
            <label
                class="mobileMenu-toggle_label"
                for="mobileMenu-toggle"
                aria-label="Open main menu"
            >
                <span class="u-isVisuallyHidden">Open main menu</span>
                <%= octicon "three-bars", height: 24 %>
            </label>
            <label
                class="mobileMenu-toggle_label"
                for="mobileMenu-user-toggle"
                aria-label="Open user menu"
            >
                <span class="u-isVisuallyHidden">Open user menu</span>
                <%= octicon "person", height: 24 %>
            </label>
        </div>

        <ul class="header-nav">
            <li class="header-nav-item">
                <%= link_to 'Orders', orders_path, class: "link" %>
            </li>
            <li class="header-nav-item">
                <%= link_to 'Assemblies', assemblies_path, class: "link" %>
            </li>
            <li class="header-nav-item">
                <%= link_to 'Items', items_path, class: "link" %>
            </li>
            <li class="header-nav-item u-isHidden_xs">
                <%= link_to 'Schedules', meal_schedules_path, class: "link" %>
            </li>
            <li class="header-nav-item u-isHidden_xs">
                <%= link_to 'Departments', departments_path, class: "link" %>
            </li>
            <li class="header-nav-item u-isHidden_xs">
                <%= link_to 'Locations', locations_path, class: "link" %>
            </li>
        </ul>

        <ul class="header-nav-user">
            <li class="header-nav-item">
                <%= link_to 'Groups', groups_path, class: "link" %>
            </li>
            <li class="header-nav-item">
                <%= link_to 'Profile', edit_user_registration_path, class: "link" %>
            </li>
            <li class="header-nav-item">
                <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "link" %>
            </li>
        </ul>
    <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Shopper</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1,user-scalable=0"/>

        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

        <style>
            .debug_dump {
                background-color: #efefef;
                border-radius: 5px;
                font-size: 14px;
                margin: 50px 5px 5px 5px;
                padding: 10px 15px;
            }
        </style>
    </head>

    <body>
        <%= render 'layouts/header' %>

        <div class="site">
            <!-- TODO: extend to support alert styles for user/session forms -->
            <%= react_component('NoticeContainer', message: notice || alert ) %>
            <%= yield %>
        </div>

        <%= render 'layouts/footer' %>

        <%= debug(params) if Rails.env.development? %>
    </body>
</html>